# Still to do
# - provide a dry-run option
# - provide a way to control saveerrors, saveoutlinks, etc.

name: "Waystation – Wayback site archiving automation"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Print what would be done without actually doing it.'
        default: false
        required: false

jobs:
  Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub pages URL
        # This stores the URL in env.PAGES_URL. The value will be "null" if
        # no pages URL is returned for any reason. Note: the URL string will
        # have double quotes around it.
        id: s1
        run: |
          echo pages_url=$(curl -s -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/caltechlibrary/foliage/pages | jq '.html_url' | tr -d '"') >> $GITHUB_ENV

      - name: Quit if GitHub pages URL is null
        id: s2
        if: startsWith(env.pages_url, 'null')
        uses: actions/github-script@v6.3.3
        with:
          script: |
            core.setFailed('Could not retrieve GitHub pages URL.')        

      - name: Proceed if have a GitHub pages URL
        id: s3
        if: startsWith(env.pages_url, 'null') != true
        uses: JamieMagee/wayback@v1.3.19
        with:
          url: ${{ env.pages_url }}
          saveErrors: false
          saveOutlinks: true
          saveScreenshot: true

      - name: Summarize the results of the run
        id: s4
        run: |
          echo \#\# Results of sending the GitHub Pages to the Wayback Machine          >> $GITHUB_STEP_SUMMARY
          echo \|-:\|-\|                                                                >> $GITHUB_STEP_SUMMARY
          echo \| Date and time of execution: \| $(date "+%F %T (%Z)") \|               >> $GITHUB_STEP_SUMMARY
          echo \| GitHub repository for this action: \| \`${{ github.repository }}\` \| >> $GITHUB_STEP_SUMMARY
          echo \| GitHub Pages URL for the repository: \| ${{ env.pages_url }}          >> $GITHUB_STEP_SUMMARY
          echo \| URL in the Wayback Machine: \| ${{ steps.s3.outputs.wayback_url }}    >> $GITHUB_STEP_SUMMARY

