# Still to do
# - print the pages_url to the github actions panel
# - print wayback_url
# - provide a dry-run option
# - provide a way to control saveerrors, saveoutlinks, etc.

name: Send the GitHub pages URL to the Wayback Machine

on:
  push:
    branches:
      - main

# ${{ github.repository }}

jobs:
  do-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub pages URL
        # This stores the URL in env.PAGES_URL. The value will be "null" if
        # no pages URL is returned for any reason. Note: the URL string will
        # have double quotes around it.
        id: step_1
        run: |
          echo pages_url=$(curl -s -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/caltechlibrary/foliage/pages | jq '.html_url' | tr -d '"') >> $GITHUB_ENV

      - name: Quit if GitHub pages URL is null
        id: step_2
        if: startsWith(env.pages_url, 'null')
        uses: actions/github-script@v6.3.3
        with:
          script: |
            core.setFailed('Could not retrieve GitHub pages URL.')        

      # - name: Proceed if have a GitHub pages URL
      #   id: step_3
      #   if: startsWith(env.pages_url, 'null') != true
      #   uses: JamieMagee/wayback@v1.3.19
      #   with:
      #     url: ${{ env.pages_url }}
      #     saveErrors: false
      #     saveOutlinks: true
      #     saveScreenshot: true

      - name: Print a summary of the results to the workflow panel
        id: step_4
        run: |
          echo "::notice title=Finished::Pages URL = ${{ env.pages_url }}"
