name: Should the github pages url

on:
  push:
    branches:
      - main

# ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Get GitHub pages URL
        run: |
          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/caltechlibrary/foliage//pages
