name: Send the GitHub pages URL to the Wayback Machine

on:
  push:
    branches:
      - main

# ${{ github.repository }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub pages URL
        # This stores the URL in env.PAGES_URL. The value will be "null" if
        # no pages URL is returned for any reason.
        id: step_1
        run: |
          echo pages_url=$(curl -s -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/caltechlibrary/foliage/pages | jq '.html_url') >> $GITHUB_ENV

      - name: Quit if GitHub pages URL is null
        id: step_2
        if: startsWith(env.pages_url, 'null')
        uses: actions/github-script@v6.3.3
        with:
          script: |
            core.setFailed('Could not retrieve GitHub pages URL.')        

      - name: Proceed if have a GitHub pages URL
        id: step_3
        if: startsWith(env.pages_url, 'null') != true
        run: |
          echo ${{ env.pages_url }}
          


  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   continue-on-error: false
  #   steps:
  #     - name: Echo GitHub pages URL
  #       run: echo ${{ env.pages_url }}
